import java.util.Arrays;

public class Main {
    private final static String trainingDataDir = "TrainingData";

    public static void main(String[] args) {
        TrainingText[] texts = TrainingText.fetchTrainingTexts(trainingDataDir);
        String[] langs = Arrays.stream(texts).map(TrainingText::getLang).distinct().toArray(String[]::new);

        Layer layer = new Layer(langs);
//        layer.train(texts);

//        //EN
//        System.out.println(layer.classify(new TrainingText("The name \"Netherlands\" in modern Polish is usually used for the historical land[10][11][12] - it refers to the countries formerly under the rule of the Habsburgs (the Habsburg Netherlands, the Spanish Netherlands, the Austrian Netherlands)[13]. After the establishment of the independent Dutch state, the Polish language initially used various names derived from the form Nederland, from the form Holland, and descriptive forms (e.g. Confederate States). After the establishment of the modern Dutch state in 1830, the name Holland was used almost exclusively in Polish (in various spelling variants), and the name \"Netherlands\" practically fell into disuse in this sense[13]. An exception is the abbreviated name of the country \"Netherlands\", recommended for use in European Union documents[14]. In October 2019, the Dutch authorities decided to abandon the English term \"Holland\", previously used in marketing regarding this country, in favor of the name \"The Netherlands\", and the implementation of the change began at the beginning of 2020. This change is domestic in nature and concerns Dutch institutions, universities, offices and embassies, etc., and does not involve an appeal to other countries to apply a similar change in their languages. This did not change the recommended short name of this country in the language", null)));
//        //FR
//        System.out.println(layer.classify(new TrainingText("Le nom « Pays-Bas » en polonais moderne est généralement utilisé pour désigner la terre historique[10][11][12] - il fait référence aux pays autrefois sous la domination des Habsbourg (Pays-Bas des Habsbourg, Pays-Bas espagnols, Pays-Bas autrichiens). [13]. Après la création de l'État néerlandais indépendant, la langue polonaise a d'abord utilisé divers noms dérivés de la forme Nederland, de la forme Holland et des formes descriptives (par exemple États confédérés). Après la création de l'État néerlandais moderne en 1830, le nom Hollande était utilisé presque exclusivement en polonais (dans diverses variantes orthographiques), et le nom « Pays-Bas » tomba pratiquement en désuétude dans ce sens[13]. Une exception est le nom abrégé du pays « Pays-Bas », dont l'utilisation est recommandée dans les documents de l'Union européenne[14]. En octobre 2019, les autorités néerlandaises ont décidé d'abandonner le terme anglais « Holland », auparavant utilisé dans le marketing concernant ce pays, au profit du nom « The Dutch », et la mise en œuvre du changement a commencé début 2020. Ce changement est de nature nationale et concerne les institutions, universités, bureaux et ambassades néerlandaises, etc., et n'implique pas un appel aux autres pays pour qu'ils appliquent un changement similaire dans leurs langues. Cela n'a pas modifié le nom court recommandé de ce pays dans la langue", null)));
//        //IT
//        System.out.println(layer.classify(new TrainingText("Il nome \"Paesi Bassi\" in polacco moderno è solitamente usato per la terra storica[10] [11] [12] - si riferisce ai paesi precedentemente sotto il dominio degli Asburgo (i Paesi Bassi asburgici, i Paesi Bassi spagnoli, i Paesi Bassi austriaci) [13]. Dopo la fondazione dello stato olandese indipendente, la lingua polacca utilizzò inizialmente vari nomi derivati \u200B\u200Bdalla forma Nederland, dalla forma Holland, e forme descrittive (ad esempio Stati Confederati). Dopo la fondazione del moderno Stato olandese nel 1830, il nome Olanda fu usato quasi esclusivamente in polacco (in varie varianti ortografiche), e il nome \"Paesi Bassi\" in questo senso cadde praticamente in disuso[13]. Un'eccezione è il nome abbreviato del paese \"Paesi Bassi\", raccomandato per l'uso nei documenti dell'Unione europea[14]. Nell'ottobre 2019, le autorità olandesi hanno deciso di abbandonare il termine inglese \"Holland\", precedentemente utilizzato nel marketing relativo a questo paese, a favore del nome \"The Netherlands\", e l'implementazione del cambiamento è iniziata all'inizio del 2020. Questo cambiamento è di natura nazionale e riguarda istituzioni, università, uffici e ambasciate olandesi, ecc., e non comporta un appello ad altri paesi affinché applichino un cambiamento simile nelle loro lingue. Ciò non ha modificato il nome breve consigliato di questo paese nella lingua", null)));
//        //PL
//        System.out.println(layer.classify(new TrainingText("Nazwa „Niderlandy” we współczesnym języku polskim stosowana jest zazwyczaj dla krainy historycznej[10][11][12] – odnosi się do krajów dawniej pozostających we władaniu Habsburgów (Niderlandy Habsburskie, Niderlandy Hiszpańskie, Niderlandy Austriackie)[13]. Po powstaniu niepodległego państwa holenderskiego w języku polskim stosowane początkowo były różne nazwy pochodzące od formy Nederland, od formy Holland oraz formy opisowe (np. Stany Skonfederowane). Po powstaniu współczesnego państwa holenderskiego w 1830 roku w języku polskim używano niemal wyłącznie nazwy Holandia (w różnych wariantach zapisu), zaś nazwa „Niderlandy” wyszła praktycznie z użycia w tym znaczeniu[13]. Wyjątkiem jest skrócona nazwa państwa „Niderlandy”, zalecana do stosowania w dokumentach Unii Europejskiej[14]. W październiku 2019 r. władze holenderskie postanowiły, że zrezygnują z anglojęzycznego określenia „Holland”, dotychczas stosowanego w marketingu dotyczącym tego kraju, na rzecz nazwy „The Netherlands”, a wprowadzanie zmiany rozpoczęto z początkiem roku 2020. Zmiana ta ma charakter wewnątrzkrajowy i dotyczy holenderskich instytucji, uniwersytetów, urzędów i ambasad itd., nie wiąże się zaś z apelem do innych państw o zastosowanie analogicznej zmiany w ich językach. Nie wpłynęło to na zmianę zalecanej krótkiej nazwy tego państwa w języku", null)));
//        //PT
//        System.out.println(layer.classify(new TrainingText("O nome \"Holanda\" em polonês moderno é geralmente usado para designar a terra histórica [10] [11] [12] - refere-se aos países anteriormente sob o domínio dos Habsburgos (os Países Baixos dos Habsburgos, os Países Baixos espanhóis, os Países Baixos austríacos) [13]. Após o estabelecimento do estado holandês independente, a língua polaca utilizou inicialmente vários nomes derivados da forma Nederland, da forma Holanda e formas descritivas (por exemplo, Estados Confederados). Após o estabelecimento do estado holandês moderno em 1830, o nome Holanda foi usado quase exclusivamente em polaco (em várias variantes ortográficas), e o nome \"Holanda\" praticamente caiu em desuso neste sentido[13]. Uma exceção é o nome abreviado do país \"Holanda\", recomendado para uso em documentos da União Europeia[14]. Em outubro de 2019, as autoridades neerlandesas decidiram abandonar o termo inglês “Holland”, anteriormente utilizado no marketing deste país, em favor do nome “Holanda”, e a implementação da mudança começou no início de 2020. Esta mudança é de natureza nacional e diz respeito a instituições, universidades, escritórios e embaixadas holandesas, etc., e não envolve um apelo a outros países para que apliquem uma mudança semelhante nas suas línguas. Isso não alterou o nome abreviado recomendado para este país no idioma", null)));

        UI.start(layer, texts);
    }
}
